library(shiny)

source("final_code.R")

ui = fluidPage(
    tabsetPanel(
      tabPanel("Introduction", fluid = TRUE,
               p("In the past couple of years during and after the COVID-19 pandemic, 
               Netflix has quickly become one of the most prominent media corporations across the globe, 
               with many millions of subscribers and a massive content library of diverse movies and television shows. 
               During this time, the streaming giant has seen its fair share of tumultuous growth and loss cycles, 
               but nevertheless, many sources indicate Netflix’s plans for a large-scale expansion into global markets 
               outside of the United States where it originated from."),
               br(),
               p("For our INFO 201 Final Project, we would like to investigate 
               Netflix’s global expansion strategy further and answer the question, 
               “Do countries with the fastest growing economies correspond with the global regions 
               from which Netflix is investing in the most streaming content?” Using data wrangling 
               and analysis methods, we will use country-specific per-capita GDP (gross domestic product) 
               values over time and compare that to global Netflix data about the release dates and countries 
               of origin of newly added movies and episodic series. With these learnings, we seek to determine 
               whether it is possible to predict future loci of high economic growth based on current 
               Netflix content investment trends."),
               br(),
               p("Netflix plans for its global expansion scheme to be accomplished by targeting subscribers 
               from a careful selection of local markets around the world. By focusing on countries outside of 
               the United States, Netflix has quickly begun to reach a wider, international audience, leading to 
               its unprecedented subscriber growth as a global media giant in recent years. To reach geographically 
               distant countries, the company began licensing mass amounts of locally-produced shows and movies from 
               hundreds of different languages in order to attract native speakers onto the platform. 
               The COVID-19 pandemic and sudden transition to online, stay-at-home lifestyles only accelerated 
               the growth of streaming services on a global scale, especially that of Netflix. During this time, 
               many foreign-language Netflix series - such as the Korean “Squid Game”, for instance - made a breakthrough 
               in the international pop-culture scene. The massive revenue generated by this series alone was a big catalyst 
               for Netflix's largescale global investment in content produced for and from the Asia-Pacific region. 
               Coincidentally, Asian countries such as China, Vietnam, Indonesia, and India are among 
               the fastest-growing economies based on their Economic Complexity Index (ECI), 
               according to researchers from Harvard University. Netflix’s choice of investment 
               in this region appears indicative of the high possibility of securing the most profitable returns, 
               as predicted by the rapidly growing economies of these countries. Under this premise, 
               we seek to draw a relationship between individual countries' economic growth with the influx of 
               new streaming content originating from said countries."),
               br(),
               p("By investigating the question of whether Netflix’s global content expansion strategy 
               corresponds with country-specific GDP growth, we will provide valuable insights for other 
               similar companies who wish to expand their own operations into international consumer markets. 
               Additionally, our findings can help predict potential increases in employment rates across the world, 
               as Netflix will undoubtedly create many local employment opportunities in the countries where it invests 
               into the most content from, further boosting the economical environments of said countries. From a business angle,
               understanding how global markets are performing is essential for profit optimization, 
               and from a political perspective, tracking foreign investments into one’s own country can serve 
               as predictors for future local economic growth. As such, our research is both interesting and important 
               due to its wide range of applications in many sectors of our international society.")
      ),
      tabPanel("Drill-Down", fluid = TRUE
               
      ),
      tabPanel("Change over time", fluid = TRUE
               
      ),
      tabPanel("Contrast", fluid = TRUE,
               sidebarLayout(
                 sidebarPanel(
                   sliderInput(
                     inputId = "yr",
                     label = "Filter by year",
                     min = 2000,
                     max = 2020,
                     value = 21),
                   
                   checkboxInput(
                     inputId = "US",
                     label = "Include United States?",
                     value = TRUE
                   ),
                   p("To answer our initial idea of whether Netflix investment 
                   coincides with the GDP growth of a country, we will compare and contrast 
                   the countries that experienced the most significant GDP growth rate in
                   the respective year with the countries with the most Netflix content in the same year."),
                   br(),
                   p("In order to do so, we first need to find out the ranking of countries 
                     on both occasions from our finalized dataset. Then, we sort the ranking 
                     of the countries from the highest to the lowest number of releases on the bar charts.
                     It is important to note that user can opt in or out the United States from the ranking 
                     to see its impact on the chart because of the fact that Netflix originated there. 
                     China, on the other hand, even though the service is not available there, 
                     releases from there are still worth considering."),
                   br(),
                   p("From the charts, we establish that the countries with the biggest GDP growth 
                     do not necessarily have the most Netflix content. The charts shows that 
                     the content released by the fastest-growing countries in 2020 is substantially 
                     lower than the countries with the most Netflix releases. To augment this contrast, 
                     there is a noticeable rising trend for the countries with the most Netflix content, 
                     while the other group exhibits no consistent pattern. Interestingly, 
                     the pandemic might have impacted content production as most of the countries display a decline in releases.
                     Nevertheless, outside of the few circumstances when the highest GDP countries surpass the top Netflix countries, 
                     Netflix content additions are not dependent on a country's economic growth.")
                 ),
                 mainPanel(
                   p("The bar chart below shows the top 10 ranking of the countries with the
                     most Netflix releases in the selected year."),
                   plotOutput("netflix_plot"),
                   p("The bar chart below shows the Netflix releases of the top 10 countries 
                     with the highest GDP growth in the selected year"),
                   plotOutput("gdp_plot"),
                   p("The line chart below shows the content addition over the years for the countries
                     with the highest releases in the selected year"),
                   plotOutput("netflix_overtime"),
                   p("The line chart below shows the content addition over the years for the countries
                     with the highest GDP growth in the selected year"),
                   plotOutput("gdp_overtime")
                 )
               )
      ),
      tabPanel("Conclusion", fluid = TRUE
               
      ),
      tabPanel("About", fluid = TRUE
               
      ),
    )
)

server <- function(input, output){
  output$netflix_plot <- renderPlot({
    if (input$US == FALSE){
      project_df <- filter(project_df, Country_of_Origin != "United States")
    }
    top_netflix(project_df, input$yr)
  })
  
  output$gdp_plot <- renderPlot({
    if (input$US == FALSE){
      project_df <- filter(project_df, Country_of_Origin != "United States")
    }
    top_gdp(project_df, input$yr)
  })
  
  output$netflix_overtime <- renderPlot({
    if (input$US == FALSE){
      project_df <- filter(project_df, Country_of_Origin != "United States")
    }
    netflix_overtime(project_df, input$yr)
  })
  
  output$gdp_overtime <- renderPlot({
    if (input$US == FALSE){
      project_df <- filter(project_df, Country_of_Origin != "United States")
    }
    gdp_overtime(project_df, input$yr)
  })
}

shinyApp(ui, server)