library(shiny)

source("final_code.R")

ui = fluidPage(
    tabsetPanel(
      tabPanel("Introduction", fluid = TRUE,
               titlePanel("Netflix Content vs. GDP Growth by Country"),
               h3("Do countries with the fastest growing economies correspond with the countries 
               from which Netflix is investing in the most streaming content?"),
               p("In the past couple of years during and after the COVID-19 pandemic, 
               Netflix has quickly become one of the most prominent media corporations across the globe, 
               with many millions of subscribers and a massive content library of diverse movies and television shows. 
               During this time, the streaming giant has seen its fair share of tumultuous growth and loss cycles, 
               but nevertheless, many sources indicate Netflix’s plans for a large-scale expansion into global markets 
               outside of the United States where it originated from."),
               br(),
               p("For our INFO 201 Final Project, we would like to investigate 
               Netflix’s global expansion strategy further and answer the question, 
               “Do countries with the fastest growing economies correspond with the global regions 
               from which Netflix is investing in the most streaming content?” Using data wrangling 
               and analysis methods, we will use country-specific per-capita GDP (gross domestic product) 
               values over time and compare that to global Netflix data about the release dates and countries 
               of origin of newly added movies and episodic series. With these learnings, we seek to determine 
               whether it is possible to predict future loci of high economic growth based on current 
               Netflix content investment trends."),
               br(),
               p("Netflix plans for its global expansion scheme to be accomplished by targeting subscribers 
               from a careful selection of local markets around the world. By focusing on countries outside of 
               the United States, Netflix has quickly begun to reach a wider, international audience, leading to 
               its unprecedented subscriber growth as a global media giant in recent years. To reach geographically 
               distant countries, the company began licensing mass amounts of locally-produced shows and movies from 
               hundreds of different languages in order to attract native speakers onto the platform. 
               The COVID-19 pandemic and sudden transition to online, stay-at-home lifestyles only accelerated 
               the growth of streaming services on a global scale, especially that of Netflix. During this time, 
               many foreign-language Netflix series - such as the Korean “Squid Game”, for instance - made a breakthrough 
               in the international pop-culture scene. The massive revenue generated by this series alone was a big catalyst 
               for Netflix's largescale global investment in content produced for and from the Asia-Pacific region. 
               Coincidentally, Asian countries such as China, Vietnam, Indonesia, and India are among 
               the fastest-growing economies based on their Economic Complexity Index (ECI), 
               according to researchers from Harvard University. Netflix’s choice of investment 
               in this region appears indicative of the high possibility of securing the most profitable returns, 
               as predicted by the rapidly growing economies of these countries. Under this premise, 
               we seek to draw a relationship between individual countries' economic growth with the influx of 
               new streaming content originating from said countries."),
               br(),
               p("By investigating the question of whether Netflix’s global content expansion strategy 
               corresponds with country-specific GDP growth, we will provide valuable insights for other 
               similar companies who wish to expand their own operations into international consumer markets. 
               Additionally, our findings can help predict potential increases in employment rates across the world, 
               as Netflix will undoubtedly create many local employment opportunities in the countries where it invests 
               into the most content from, further boosting the economical environments of said countries. From a business angle,
               understanding how global markets are performing is essential for profit optimization, 
               and from a political perspective, tracking foreign investments into one’s own country can serve 
               as predictors for future local economic growth. As such, our research is both interesting and important 
               due to its wide range of applications in many sectors of our international society.")
      ),
      tabPanel("Drill-Down", fluid = TRUE,
               titlePanel("Number of Netflix Releases By Country"),
               
               # Select number of countries for pie chart
               sidebarLayout(
                 sidebarPanel(
                   sliderInput(
                     inputId = "num_countries",
                     label = "Select a number of countries to view in the pie chart",
                     min = 1,
                     max = 60,
                     value = 10
                   ),
                   checkboxInput(
                     inputId = "USA",
                     label = "Include the United States?",
                     value = TRUE
                   ),
                   br(),
                   h1("Takeaway Message:"),
                   p(strong("As observed through both visualizations, it is obvious that the United States is a large and significant
         outlier when it comes to its contributions to the Netflix content library.")),
                   p("The United States produced more content in 2020 than the next ten countries combined. 
        This makes sense, as the US is home to both the world's largest filmmaking industry - Hollywood - 
        and Netflix's origins."),
                   p("However, we should be very mindful of the US's outlier status while performing further analysis to avoid our findings
        being too inaccurately skewed."),

                 ),
                 
                 
                 # Display the plot in the main panel
                 mainPanel(
                   plotOutput(outputId = "pie_chart"),
                   strong("Hover over the map to view exact numbers of Netflix releases for each country."), 
                   p(strong("You can also zoom in and zoom out using buttons in the top right corner.")),
                   plotlyOutput(outputId = "world_map")
                 )
                 
               ),
               
      ),
      tabPanel("Change Over Time", fluid = TRUE,
               titlePanel("Top 6 Countries Netflix Releases & GDP Growth"),
               sidebarLayout(
                 sidebarPanel(
                   h1("Control Panel"),
                   selectInput(
                     inputId = "country_name",
                     label = "Select a country",
                     choices = new_country_names
                   ),
                   strong("Tab description"),
                   p("The following page displays plots for selected country's GDP growth
                   from 2000 to 2021 as well as country's Netflix releases from 2000 to 2021.
                   In addition the page contains 2 static graphs displaying
                   6 top Netflix countries GDP growth from 2000 to 2021 and 
                     6 top Netflix countries Netflix releases from 2000 to 2021"),
                   strong("Overview:"),
                   p("To establish the groundwork for the Netflix investment pattern, we decided to identify
                   the economic growth pattern for the countries with the most Netflix content in 2020. 
                   The general assumption we made is since 2020 was a difficult time under the COVID-19 pandemic,
                   it’s reasonable to think that observing the number of releases of Netflix content from that said
                   countries should provide insight into Netflix's business plan. On this page we are  focusing on 
                   the countries that fulfill above mentioned criteria and attempt to study the Netflix content addition
                   pattern from 2000 to 2020. In addition, we also study the GDP growth pattern over the same time span. 
                   From our observation, all six countries demonstrate similar growth patterns in terms of Netflix content.
                   With the exception of Germany, the other five countries experienced a decline in the number of releases in 2020.
                     Similarly, the GDP growths of the six countries plummet to their lowest, proving the overall impact of the COVID-19 pandemic "),
                   strong("Takeaway message"),
                   p("All six countries demonstrated relatively steady GDP growth from 2000-2019, before slowing down significantly in 2020 , as a
                   result of the COVID-19 pandemic and accelerating quickly soon after , as the lockdown mandates began to end. All six countries also
                   showed a general growth in their number of contributions to Netflix content per year, despite some slowing down between 2018-2020.
                   The following findings might indicate that there is a positive correlation between the GDP growth of the top 6 Netflix-contributing countries
                     and the number of Netflix releases they produced each year between 2000-2020. However, we cannot say that this correlation is causative without further analysis.")
                 ),
                 mainPanel(
                   plotOutput(outputId = "line_graph_1"),
                   plotOutput(outputId = "line_graph_3"),
                   plotOutput(outputId = "line_graph"),
                   plotOutput(outputId = "line_graph_2")
                 )
                 
               )
      ),
      tabPanel("Contrast", fluid = TRUE,
               titlePanel("Netflix Releases from Top Content Contributors vs. Fastest Growing Countries"),
               sidebarLayout(
                 sidebarPanel(
                   sliderInput(
                     inputId = "yr",
                     label = "Filter by year",
                     min = 2000,
                     max = 2020,
                     value = 21),
                   
                   checkboxInput(
                     inputId = "US",
                     label = "Include United States?",
                     value = TRUE
                   ),
                   strong("Overview"),
                   p("To answer our initial idea of whether Netflix investment 
                   coincides with the GDP growth of a country, we will compare and contrast 
                   the countries that experienced the most significant GDP growth rate in
                   the respective year with the countries with the most Netflix content in the same year."),
                   br(),
                   p("In order to do so, we first need to find out the ranking of countries 
                     on both occasions from our finalized dataset. Then, we sort the ranking 
                     of the countries from the highest to the lowest number of releases on the bar charts.
                     It is important to note that user can opt in or out the United States from the ranking 
                     to see its impact on the chart because of the fact that Netflix originated there. 
                     China, on the other hand, even though the service is not available there, 
                     releases from there are still worth considering."),
                   br(),
                   p("From the charts, we establish that the countries with the biggest GDP growth 
                     do not necessarily have the most Netflix content. The charts shows that 
                     the content released by the fastest-growing countries in 2020 is substantially 
                     lower than the countries with the most Netflix releases. To augment this contrast, 
                     there is a noticeable rising trend for the countries with the most Netflix content, 
                     while the other group exhibits no consistent pattern. Interestingly, 
                     the pandemic might have impacted content production as most of the countries display a decline in releases.
                     Nevertheless, outside of the few circumstances when the highest GDP countries surpass the top Netflix countries, 
                     Netflix content additions are not dependent on a country's economic growth."),
                   br(),
                   strong("Takeaway message"),
                   p("A country’s economic growth does not necessarily indicate Netflix’s investment into content from that country, 
                   at least when using GDP as a guideline. There is a notable contrast between the number of releases between the two 
                   groups we studied."),
                   p("Netflix possibly considers various other factors when deciding which countries to invest in content from 
                   besides just countries with the highest potential for economic growth. These factors could include countries 
                   with large filmmaking industries (such as South Korea and India), favorable political conditions, and more.")
                 ),
                 mainPanel(
                   p("The bar chart below shows the top 10 ranking of the countries with the
                     most Netflix releases in the selected year."),
                   plotOutput("netflix_plot"),
                   p("The bar chart below shows the Netflix releases of the top 10 countries 
                     with the highest GDP growth in the selected year"),
                   plotOutput("gdp_plot"),
                   p("The line chart below shows the content addition over the years for the countries
                     with the highest releases in the selected year"),
                   plotOutput("netflix_overtime"),
                   p("The line chart below shows the content addition over the years for the countries
                     with the highest GDP growth in the selected year"),
                   plotOutput("gdp_overtime")
                 )
               )
      ),
      tabPanel("Conclusion", fluid = TRUE,
               h1("Final Takeaways"),
               br(),
               strong("After careful analysis, we did not find a strong correlation between how fast a country is growing economically 
                and the number of Netflix releases produced in said country. We conclude that while GDP growth may be one factor 
                that Netflix takes into consideration when investing in global content, GDP growth is not a good indicator of 
                Netflix’s content investments on its own."),
               br(),
               br(),
               p("Instead, there could be any number of other reasons on which Netflix bases its content strategy around, 
                including - but not limited to - geopolitical and legal factors, countries with large filmmaking industries, 
                and more. For instance, we can see that India, South Korea, and the United States are all in the top six for 
                contributions to Netflix’s content library, and coincidentally, they are all home to some of the largest filmmaking 
                industries in the world. The United States specifically was a very large and significant outlier in our data due to 
                it being both the home of Hollywood and where Netflix was founded and is currently headquartered.")
      ),
      tabPanel("About", fluid = TRUE,
               strong("App Authors"),
               br(),
               p("Aiman Hazmi Shamsul"),
               p("Alisa Tcurko"),
               p("Isha Kshirsagar"),
               br(),
               p("INFO 201 Final Project | Group 55"),
               p("Spring Quarter 2023"),
               p("University of Washington"),
               br(),
               strong("Dataset Sources"),
               br(),
               br(),
               strong("Dataset #1: “Netflix Movies and TV Shows"),
               br(),
               a("Dataset Link", href = "https://www.kaggle.com/datasets/shivamb/netflix-shows"),
               br(),
               br(),
               p("For our first source of data, we are using a comprehensive dataset of all 
               Netflix movie and episodic series titles added to the platform between December 31st, 2007, 
               and November 25th, 2021. The data table includes twelve columns with content-identifying features 
               such as type of content (movie or television series), unique ID number, title, cast and directors, 
               country of production, date added onto Netflix, the actual date of release, rating, and duration. 
               It also includes 8,807 unique rows of values. For the purposes of this data analysis project, we will 
               primarily be utilizing the columns of type of content, country of production, and date added to Netflix."),
               br(),
               p("We sourced this set from Kaggle, an online platform for uploading and downloading open-source datasets. 
               It was available in a .csv (comma-separated values) format in a Microsoft Excel spreadsheet. The dataset 
               was uploaded onto the platform by user Shivam Bansal - a certified “Datasets Grandmaster” with a rich portfolio 
               of uploaded datasets on Kaggle - but unfortunately, there is little information available regarding who actually 
               collected or generated the data and how it was sourced. Despite the limited source information we have, 
               we decided to move forward with this dataset based on factors such as Shivam Bansal’s perceived credibility 
               as a top Kaggle member and the fact that this same dataset has been used and referenced by many other users 
               for their own data projects."),
               br(),
               strong("Dataset #2: “International Macroeconomic Dataset: Real Per-Capita GDP (2015 Base) Projected”"),
               br(),
               a("Dataset Link", href = "https://ers.usda.gov/data-products/international-macroeconomic-data-set.aspx"),
               br(),
               br(),
               p("For our second source of data, we are using an expansive dataset of annual country-specific 
                 per-capita GDP values from across the world, ranging between the years 1970 and 2032. 
                 This dataset also includes separate columns that show the year-over-year GDP growth rates for each country 
                 starting from 1971 and continuing to 2032 as before. This dataset was most recently updated 
                 on November 15th, 2022, and all GDP values between 1970 and 2022 are real observed values. 
                 GDP values from 2023 onwards are forecasted predictions based on previous growth trends and 
                 current economic conditions for each country. Each GDP value has been adjusted for inflation 
                 according to the U.S. dollar’s worth in 2015. In total, the data table includes 127 columns - 
                 one of which includes the country names, and the rest is split equally between annual per-capita GDP values 
                 and annual GDP growth rates. It also includes unique rows for 216 countries, 
                 in addition to 51 other rows that include summary statistics for specific groups or regions of countries, 
                 for 267 unique rows in total"),
               br(),
               p("We sourced this dataset from the U.S. Department of Agriculture’s Economic Research Service 
               via the data.gov federal website for open-source databases. This collection of global GDP values over time 
               was created to “serve as underlying assumptions for the annual USDA agricultural supply and demand projections”, 
               and “the macroeconomic projections describe the long-term, 10-year scenario that is used as a benchmark 
               for analyzing the impacts of alternative scenarios and macroeconomic shocks”. 
               Although we are unsure how the USDA collected or generated the data, we are sure that 
               a government research organization such as this would be a trustworthy and accurate data source for our project.")
      ),
    )
)

server <- function(input, output){
  output$netflix_plot <- renderPlot({
    if (input$US == FALSE){
      project_df <- filter(project_df, Country_of_Origin != "United States")
    }
    top_netflix(project_df, input$yr)
  })
  
  output$gdp_plot <- renderPlot({
    if (input$US == FALSE){
      project_df <- filter(project_df, Country_of_Origin != "United States")
    }
    top_gdp(project_df, input$yr)
  })
  
  output$netflix_overtime <- renderPlot({
    if (input$US == FALSE){
      project_df <- filter(project_df, Country_of_Origin != "United States")
    }
    netflix_overtime(project_df, input$yr)
  })
  
  output$gdp_overtime <- renderPlot({
    if (input$US == FALSE){
      project_df <- filter(project_df, Country_of_Origin != "United States")
    }
    gdp_overtime(project_df, input$yr)
  })
  
  output$world_map <- renderPlotly({
    # Define a minimalist theme for maps
    blank_theme <- theme_bw() +
      theme(
        axis.line = element_blank(),
        # remove axis lines
        axis.text = element_blank(),
        # remove axis labels
        axis.ticks = element_blank(),
        # remove axis ticks
        axis.title = element_blank(),
        # remove axis titles
        plot.background = element_blank(),
        # remove gray background
        panel.grid.major = element_blank(),
        # remove major grid lines
        panel.grid.minor = element_blank(),
        # remove minor grid lines
        panel.border = element_blank()      # remove border around plot
      )
    
    # Create the ggplot object
    interactive_world_map <- ggplot(world_shape) +
      geom_polygon(
        mapping = aes(
          x = long,
          y = lat,
          group = group,
          fill = Releases_from_2020
        ),
        color = "black",
        size = .1
      ) +
      scale_fill_continuous(low = "#DAF5FB", high = "#03045E") +
      labs(
        title = "Countries of Origin of Netflix Content Releases in 2020",
        x = "Longitude",
        y = "Latitude",
        fill = "Number of Netflix Releases in 2020"
      ) +
      blank_theme # variable including map styles
    
    # Convert ggplot object to plotly
    ggplotly(interactive_world_map)
  })
  
  #---------------------------------------------------------------------
  
  #Pie chart:
  
  output$pie_chart <- renderPlot({
    top_x_countries <- input$num_countries
    pie_chart_fn(top_x_countries, input$USA)
    
  })
  
  #---------------------------------------------------------------------

  output$line_graph_2 <- renderPlot({
    line_3 <-ggplot(data=d_2, aes(x=release_year,y=value,col=variable)) +
      geom_line()+ggtitle("Netflix releases all countries")+
      xlab("Year")+ylab("Number of Netflix releases")+labs(color="Countries")
    return(line_3)
  })  
  output$line_graph_3 <- renderPlot({
    line_5 <-ggplot(data=releases_df, aes(x=release_year,y=releases_df[,input$country_name], col=input$country_name)) +
      geom_line()+ ggtitle("Plot of the selected country's Netflix releases")+
      xlab("Year")+ylab("Number of Netflix releases")+labs(color="Country")
    return(line_5)
    
  }) 
  
  output$line_graph <- renderPlot({
    line_4 <-ggplot(data=d, aes(x=GDP_Growth_per_yr,y=value,col=variable)) +
      geom_line()+ggtitle("All countries GDP growth")+
      xlab("Year")+ylab("GDP growth")+labs(color="Countries")
    return(line_4)
  })
  output$line_graph_1 <- renderPlot({
    line_6 <-ggplot(data=gdp_df, aes(x=GDP_Growth_per_yr,y=gdp_df[,input$country_name], col=input$country_name)) +
      geom_line()+ ggtitle("Plot of the selected country's GDP growth")+
      xlab("Year")+ylab("GDP growth")+labs(color="Country")
    return(line_6)
  })

}



shinyApp(ui, server)