library(shiny)

source("final_code.R")

ui = fluidPage(
    tabsetPanel(
      tabPanel("Introduction", fluid = TRUE,
               p("In the past couple of years during and after the COVID-19 pandemic, 
               Netflix has quickly become one of the most prominent media corporations across the globe, 
               with many millions of subscribers and a massive content library of diverse movies and television shows. 
               During this time, the streaming giant has seen its fair share of tumultuous growth and loss cycles, 
               but nevertheless, many sources indicate Netflix’s plans for a large-scale expansion into global markets 
               outside of the United States where it originated from."),
               br(),
               p("For our INFO 201 Final Project, we would like to investigate 
               Netflix’s global expansion strategy further and answer the question, 
               “Do countries with the fastest growing economies correspond with the global regions 
               from which Netflix is investing in the most streaming content?” Using data wrangling 
               and analysis methods, we will use country-specific per-capita GDP (gross domestic product) 
               values over time and compare that to global Netflix data about the release dates and countries 
               of origin of newly added movies and episodic series. With these learnings, we seek to determine 
               whether it is possible to predict future loci of high economic growth based on current 
               Netflix content investment trends."),
               br(),
               p("Netflix plans for its global expansion scheme to be accomplished by targeting subscribers 
               from a careful selection of local markets around the world. By focusing on countries outside of 
               the United States, Netflix has quickly begun to reach a wider, international audience, leading to 
               its unprecedented subscriber growth as a global media giant in recent years. To reach geographically 
               distant countries, the company began licensing mass amounts of locally-produced shows and movies from 
               hundreds of different languages in order to attract native speakers onto the platform. 
               The COVID-19 pandemic and sudden transition to online, stay-at-home lifestyles only accelerated 
               the growth of streaming services on a global scale, especially that of Netflix. During this time, 
               many foreign-language Netflix series - such as the Korean “Squid Game”, for instance - made a breakthrough 
               in the international pop-culture scene. The massive revenue generated by this series alone was a big catalyst 
               for Netflix's largescale global investment in content produced for and from the Asia-Pacific region. 
               Coincidentally, Asian countries such as China, Vietnam, Indonesia, and India are among 
               the fastest-growing economies based on their Economic Complexity Index (ECI), 
               according to researchers from Harvard University. Netflix’s choice of investment 
               in this region appears indicative of the high possibility of securing the most profitable returns, 
               as predicted by the rapidly growing economies of these countries. Under this premise, 
               we seek to draw a relationship between individual countries' economic growth with the influx of 
               new streaming content originating from said countries."),
               br(),
               p("By investigating the question of whether Netflix’s global content expansion strategy 
               corresponds with country-specific GDP growth, we will provide valuable insights for other 
               similar companies who wish to expand their own operations into international consumer markets. 
               Additionally, our findings can help predict potential increases in employment rates across the world, 
               as Netflix will undoubtedly create many local employment opportunities in the countries where it invests 
               into the most content from, further boosting the economical environments of said countries. From a business angle,
               understanding how global markets are performing is essential for profit optimization, 
               and from a political perspective, tracking foreign investments into one’s own country can serve 
               as predictors for future local economic growth. As such, our research is both interesting and important 
               due to its wide range of applications in many sectors of our international society.")
      ),
      tabPanel("Drill-Down", fluid = TRUE
               
      ),
      tabPanel("Change over time", fluid = TRUE,
               sidebarLayout(
                 sidebarPanel(
                   h1("Control Panel"),
                   selectInput(
                     inputId = "country_name",
                     label = "Select a country",
                     choices = new_country_names
                   ),
                   strong("Tab description"),
                   p("The following page displays plots for selected country's GDP growth
                   from 2000 to 2021 as well as country's Netflix releases from 2000 to 2021.
                   In addition the page contains 2 static graphs displaying
                   6 top Netflix countries GDP growth from 2000 to 2021 and 
                     6 top Netflix countries Netflix releases from 2000 to 2021"),
                   strong("Overview:"),
                   p("To establish the groundwork for the Netflix investment pattern, we decided to identify
                   the economic growth pattern for the countries with the most Netflix content in 2020. 
                   The general assumption we made is since 2020 was a difficult time under the COVID-19 pandemic,
                   it’s reasonable to think that observing the number of releases of Netflix content from that said
                   countries should provide insight into Netflix's business plan. On this page we are  focusing on 
                   the countries that fulfill above mentioned criteria and attempt to study the Netflix content addition
                   pattern from 2000 to 2020. In addition, we also study the GDP growth pattern over the same time span. 
                   From our observation, all six countries demonstrate similar growth patterns in terms of Netflix content.
                   With the exception of Germany, the other five countries experienced a decline in the number of releases in 2020.
                     Similarly, the GDP growths of the six countries plummet to their lowest, proving the overall impact of the COVID-19 pandemic "),
                   strong("Takeaway message"),
                   p("All six countries demonstrated relatively steady GDP growth from 2000-2019, before slowing down significantly in 2020 , as a
                   result of the COVID-19 pandemic and accelerating quickly soon after , as the lockdown mandates began to end. All six countries also
                   showed a general growth in their number of contributions to Netflix content per year, despite some slowing down between 2018-2020.
                   The following findings might indicate that there is a positive correlation between the GDP growth of the top 6 Netflix-contributing countries
                     and the number of Netflix releases they produced each year between 2000-2020. However, we cannot say that this correlation is causative without further analysis.")
                 ),
                 mainPanel(
                   plotOutput(outputId = "line_graph_1"),
                   plotOutput(outputId = "line_graph_3"),
                   plotOutput(outputId = "line_graph"),
                   plotOutput(outputId = "line_graph_2")
                 )
                 
               )
      ),
      tabPanel("Contrast", fluid = TRUE,
               sidebarLayout(
                 sidebarPanel(
                   sliderInput(
                     inputId = "yr",
                     label = "Filter by year",
                     min = 2000,
                     max = 2020,
                     value = 21),
                   
                   checkboxInput(
                     inputId = "US",
                     label = "Include United States?",
                     value = TRUE
                   ),
                   p("To answer our initial idea of whether Netflix investment 
                   coincides with the GDP growth of a country, we will compare and contrast 
                   the countries that experienced the most significant GDP growth rate in
                   the respective year with the countries with the most Netflix content in the same year."),
                   br(),
                   p("In order to do so, we first need to find out the ranking of countries 
                     on both occasions from our finalized dataset. Then, we sort the ranking 
                     of the countries from the highest to the lowest number of releases on the bar charts.
                     It is important to note that user can opt in or out the United States from the ranking 
                     to see its impact on the chart because of the fact that Netflix originated there. 
                     China, on the other hand, even though the service is not available there, 
                     releases from there are still worth considering."),
                   br(),
                   p("From the charts, we establish that the countries with the biggest GDP growth 
                     do not necessarily have the most Netflix content. The charts shows that 
                     the content released by the fastest-growing countries in 2020 is substantially 
                     lower than the countries with the most Netflix releases. To augment this contrast, 
                     there is a noticeable rising trend for the countries with the most Netflix content, 
                     while the other group exhibits no consistent pattern. Interestingly, 
                     the pandemic might have impacted content production as most of the countries display a decline in releases.
                     Nevertheless, outside of the few circumstances when the highest GDP countries surpass the top Netflix countries, 
                     Netflix content additions are not dependent on a country's economic growth.")
                 ),
                 mainPanel(
                   p("The bar chart below shows the top 10 ranking of the countries with the
                     most Netflix releases in the selected year."),
                   plotOutput("netflix_plot"),
                   p("The bar chart below shows the Netflix releases of the top 10 countries 
                     with the highest GDP growth in the selected year"),
                   plotOutput("gdp_plot"),
                   p("The line chart below shows the content addition over the years for the countries
                     with the highest releases in the selected year"),
                   plotOutput("netflix_overtime"),
                   p("The line chart below shows the content addition over the years for the countries
                     with the highest GDP growth in the selected year"),
                   plotOutput("gdp_overtime")
                 )
               )
      ),
      tabPanel("Conclusion", fluid = TRUE,
               textOutput(outputId = "final_text")
               
      ),
      tabPanel("About", fluid = TRUE
               
      ),
    )
)

server <- function(input, output){
  output$netflix_plot <- renderPlot({
    if (input$US == FALSE){
      project_df <- filter(project_df, Country_of_Origin != "United States")
    }
    top_netflix(project_df, input$yr)
  })
  
  output$gdp_plot <- renderPlot({
    if (input$US == FALSE){
      project_df <- filter(project_df, Country_of_Origin != "United States")
    }
    top_gdp(project_df, input$yr)
  })
  
  output$netflix_overtime <- renderPlot({
    if (input$US == FALSE){
      project_df <- filter(project_df, Country_of_Origin != "United States")
    }
    netflix_overtime(project_df, input$yr)
  })
  
  output$gdp_overtime <- renderPlot({
    if (input$US == FALSE){
      project_df <- filter(project_df, Country_of_Origin != "United States")
    }
    gdp_overtime(project_df, input$yr)
  })
  output$line_graph_2 <- renderPlot({
    line_3 <-ggplot(data=d_2, aes(x=release_year,y=value,col=variable)) +
      geom_line()+ggtitle("Netflix releases all countries")+
      xlab("Year")+ylab("Number of Netflix releases")+labs(color="Countries")
    return(line_3)
  })  
  output$line_graph_3 <- renderPlot({
    line_5 <-ggplot(data=releases_df, aes(x=release_year,y=releases_df[,input$country_name], col=input$country_name)) +
      geom_line()+ ggtitle("Plot of the selected country's Netflix releases")+
      xlab("Year")+ylab("Number of Netflix releases")+labs(color="Country")
    return(line_5)
    
  }) 
  
  output$line_graph <- renderPlot({
    line_4 <-ggplot(data=d, aes(x=GDP_Growth_per_yr,y=value,col=variable)) +
      geom_line()+ggtitle("All countries GDP growth")+
      xlab("Year")+ylab("GDP growth")+labs(color="Countries")
    return(line_4)
  })
  output$line_graph_1 <- renderPlot({
    line_6 <-ggplot(data=gdp_df, aes(x=GDP_Growth_per_yr,y=gdp_df[,input$country_name], col=input$country_name)) +
      geom_line()+ ggtitle("Plot of the selected country's GDP growth")+
      xlab("Year")+ylab("GDP growth")+labs(color="Country")
    return(line_6)
  })
  output$final_text<-renderText({
    "The final conclusion that we achieved as a result of our analysis
  can be stated as follows:'After careful analysis we didn't find a strong correlation 
  between any country's GDP growth and the number of Netflix releases produced in this 
  country'. We conclude that GDP growth is not an indicator of country's original Netflix production
  and there could be any number of other reasons on which Netflix bases 
  its decision when selecting a country for originals production"
  })
}

shinyApp(ui, server)